# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a42772b2b498eda321955db864b92475"
name = "ReviewSocial"
application_url = "https://reviewsocial-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/gdpr/customers_data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/gdpr/customers_redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/gdpr/shop_redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://reviewsocial-production.up.railway.app/auth/callback",
  "https://reviewsocial-production.up.railway.app/auth/login",
  "https://reviewsocial-production.up.railway.app/api/auth"
]
